#!/bin/sh /etc/rc.common
# 
# kea-dhcp4 - OpenWrt init script for Kea DHCPv4 server
#
# Copyright (C) 2025 Liu Yu <f78fk@live.com>
#
# This file is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.
# You may obtain a copy of the license at:
# https://creativecommons.org/licenses/by-sa/4.0/
#
# You are free to share and adapt this file under the terms of the license,
# as long as you give appropriate credit and distribute contributions under the same license.
#
# Version: 1.0.0
# Date: 2025-07-13

START=90
STOP=10

USE_PROCD=1
NAME=kea-dhcp4
DAEMON=/usr/sbin/kea-dhcp4
CONFIG=/etc/kea/kea-dhcp4.conf
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

start_service() {
    mkdir -p /var/run/kea
    chown root:root /var/run/kea
    chmod 755 /var/run/kea

     echo "Checking /var/lib/kea directory and lease file..."
    if [ ! -d /var/lib/kea ]; then
        mkdir -p /var/lib/kea
        echo "Created directory /var/lib/kea"
    fi

    if [ ! -f /var/lib/kea/kea-leases4.csv ]; then
        touch /var/lib/kea/kea-leases4.csv
        echo "Created empty lease file /var/lib/kea/kea-leases4.csv"
    fi

    chmod 644 /var/lib/kea/kea-leases4.csv
    chown root:root /var/lib/kea/kea-leases4.csv

    echo "Starting $NAME..."
    procd_open_instance
    procd_set_param command $DAEMON -c $CONFIG
    procd_set_param stdout $LOGFILE
    procd_set_param stderr $LOGFILE
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    echo "Stopping $NAME..."
    if [ -f $PIDFILE ]; then
        kill $(cat $PIDFILE) && rm -f $PIDFILE
    fi
}

status_service() {
    if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
        echo "$NAME is running (PID $(cat $PIDFILE))"
        return 0
    else
        echo "$NAME is not running"
        return 1
    fi
}
